name: GitHub Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git credentials for private repos
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials

      - name: Check Git authentication
        run: |
          git ls-remote https://github.com/tkoncz/py-private-pkg-build-example.git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the project
        run: uv build
