name: GitHub Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Configure Git credentials for private repos I
      #   run: |
      #     echo "https://${{ secrets.GH_PAT }}@github.com" > /tmp/git-credentials
      #     git config --global credential.helper "store --file=/tmp/git-credentials"
      #     git config --global --get credential.helper  # verify
      #     cat /tmp/git-credentials  # will show masked token

      - name: Configure Git credentials for private repos II
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
          git config --global --get-regexp url

      # - name: Verify Git config
      #   run: git config --list 

      # - name: Verify Git credentials
      #   run: |
      #     # Check if the credentials file exists and has the correct URL format without printing the token
      #     if grep -q "https://ghp_.*@github.com" /tmp/git-credentials; then
      #       echo "Git credentials file contains the correct URL format."
      #     else
      #       echo "Git credentials file is missing or incorrect!" && exit 1
      #     fi

      - name: Check Git authentication 1
        run: |
          git ls-remote https://${{ secrets.GH_PAT }}@github.com/tkoncz/py-private-pkg-build-example.git

      - name: Check Git authentication 2
        run: |
          git ls-remote https://github.com/tkoncz/py-private-pkg-build-example.git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the project
        run: uv build
